# Generated by Django 4.2.7 on 2023-11-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('citizen_id', models.CharField(max_length=10)),
                ('city', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Tehran'), (2, 'Tabriz'), (3, 'Esfahan'), (4, 'Shiraz'), (5, 'Karaj'), (6, 'Mashhad'), (7, 'Gom'), (8, 'Ahvaz'), (9, 'Kermanshah'), (10, 'Rasht'), (11, 'Urmia'), (12, 'Zahedan'), (13, 'Hamadan'), (14, 'Kerman'), (15, 'Yazd'), (16, 'Ardabil'), (17, 'BandarAbbas'), (18, 'Arak')], null=True)),
                ('address', models.CharField(max_length=150)),
                ('clinic_license', models.ImageField(upload_to='clinic/license')),
                ('is_approver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile')),
            ],
        ),
    ]
