# Generated by Django 4.2.7 on 2024-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsetting',
            name='closing_time',
            field=models.TimeField(blank=True, default='20:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='opening_time',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
    ]
