# Generated by Django 4.2.7 on 2024-01-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_review_comment_clinicsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
