# Generated by Django 4.2.7 on 2024-01-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('role', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Clinic'), (3, 'Laboratory')], null=True)),
                ('data_join', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_picture')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='users/cover_photos')),
                ('citizen_id', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Tehran'), (2, 'Tabriz'), (3, 'Esfahan'), (4, 'Shiraz'), (5, 'Karaj'), (6, 'Mashhad'), (7, 'Gom'), (8, 'Ahvaz'), (9, 'Kermanshah'), (10, 'Rasht'), (11, 'Urmia'), (12, 'Zahedan'), (13, 'Hamadan'), (14, 'Kerman'), (15, 'Yazd'), (16, 'Ardabil'), (17, 'BandarAbbas'), (18, 'Arak')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
