# Generated by Django 4.2.7 on 2024-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientRating', models.BooleanField(default=False)),
                ('patientComment', models.BooleanField(default=False)),
                ('patientSignUp', models.BooleanField(default=False)),
                ('patientLogin', models.BooleanField(default=False)),
                ('clinicRating', models.BooleanField(default=False)),
                ('clinicComment', models.BooleanField(default=False)),
                ('clinicSignUp', models.BooleanField(default=False)),
                ('clinicLogin', models.BooleanField(default=False)),
            ],
        ),
    ]
