# Generated by Django 4.2.7 on 2024-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permission_answerquestion_permission_askquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='clinicAppointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='patientAppointment',
            field=models.BooleanField(default=False),
        ),
    ]
